### ISSUE TITLE
Uthenting DefaultRights for et system.

### ISSUE THREAD

**Issue by lovoll** [Altinn/altinn-authentication#587]
### Description of the bug

Feil ved uthenting av DefaultRights for et system

GET https://platform.at22.altinn.cloud/authentication/api/v1/systemregister er benyttet i forkant for å finne en liste over systemer.
Med en pålogget bruker

### Steps To Reproduce

1. Gjør følgende kall: GET https://platform.at22.altinn.cloud/authentication/api/v1/systemregister/product/96ea3185-23cc-4df5-88f3-d43fbd995fd3

med en Studio Runtime cookie for 55846201709 som er satt opp som daglig leder i 314330897 (Hacket inn i AT22 siden han bare er Kontaktperson i følge ER registeret)

Dette medfører en responce med status kode 500 og følgende innhold:

Npgsql.PostgresException (0x80004005): 42703: column "unnest" does not exist

POSITION: 25
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSourceCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSourceCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Altinn.Platform.Authentication.Persistance.Extensions.NpgSqlExtensions.ExecuteEnumerableAsync(NpgsqlCommand cmd, CancellationToken cancellationToken)+MoveNext() in /app/src/Persistance/Extensions/NpgSqlExtensions.cs:line 24
   at Altinn.Platform.Authentication.Persistance.Extensions.NpgSqlExtensions.ExecuteEnumerableAsync(NpgsqlCommand cmd, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIteratorWithTask`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs:line 392
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Altinn.Platform.Authentication.Persistance.RepositoryImplementations.SystemRegisterRepository.GetDefaultRightsForRegisteredSystem(String systemId) in /app/src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs:line 198
   at Altinn.Platform.Authentication.Persistance.RepositoryImplementations.SystemRegisterRepository.GetDefaultRightsForRegisteredSystem(String systemId) in /app/src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs:line 198
   at Altinn.Authentication.Controllers.SystemRegisterController.GetDefaultRightsForRegisteredSystem(String productId, CancellationToken cancellationToken) in /app/src/Authentication/Controllers/SystemRegisterController.cs:line 57
   at lambda_method515(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column "unnest" does not exist
    Position: 25
    File: parse_relation.c
    Line: 3666
    Routine: errorMissingColumn

HEADERS
=======
Accept: */*
Host: internal.platform.at22.altinn.cloud
User-Agent: PostmanRuntime/7.39.0
Accept-Encoding: gzip,deflate,br
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM4OTJENDgyRTYyMDI2NzI1MTJBRTBDMkQ5REJBQzBERTRBNEVDMzciLCJ4NXQiOiJPSkxVZ3VZZ0puSlJLdURDMmR1c0RlU2s3RGMiLCJ0eXAiOiJKV1QifQ.eyJuYW1laWQiOiIyMDAxMjM3MiIsInVybjphbHRpbm46dXNlcmlkIjoiMjAwMTIzNzIiLCJ1cm46YWx0aW5uOnBhcnR5aWQiOjUxMDM2MTQ3LCJ1cm46YWx0aW5uOmF1dGhlbnRpY2F0ZW1ldGhvZCI6IklkcG9ydGVuVGVzdElkIiwidXJuOmFsdGlubjphdXRobGV2ZWwiOjQsImp0aSI6IjQyNmEwMDlhLTkzYjItNDEzYi04NTY0LTc3MmVjYzdjODYzYyIsIm5iZiI6MTcxODE4ODgyMywiZXhwIjoxNzE4MTkwNjIzLCJpYXQiOjE3MTgxODg4MjN9.j7pRFIaQU_9SGOw8InwT8UTkIGG_JyQTlQ_F67Dxt8632rTx18L796LyFDUhcNjNqVE3dOHETCu5MezWc37MxZ8ACW639t-RJ5-7sJD-kyWcvj66OQtHhtVcdZJyo4lN7xjh5WCPe3ZZTjxTMRCz5Qp6WAEEjR4fSk4O0O-I8UrSjxk82fvrnnjnM-nFLYUc4PlTQ79Z1WOOOBklzHDVozyDywSJlbAeMMsfh2VgZBw_zYpfd2j8aRR-yFvshRUbTpmAp7-RXm0Wx76iIfwT95DUvjEwYgHvjvIzV4E5s-rPxz37ZFQVaroQSB-vhCB1GNdw3ryz_phlXsagV_QUXw
Request-Id: |44baebfc-464435845b4de057.44baebfd_
l5d-dst-override: altinn-authentication.default.svc.cluster.local:80
postman-token: 5cf66356-1eca-44a8-bca5-54057b2d986a
x-forwarded-host: internal.platform.at22.altinn.cloud
x-forwarded-port: 443
x-forwarded-proto: https
x-forwarded-server: altinn-traefik-78db8c4c57-qt6jq
x-real-ip: 10.122.0.195
l5d-client-id: altinn-traefik.traefik.serviceaccount.identity.linkerd.cluster.local
X-Original-For: [::ffff:10.122.0.127]:47320

**Comment by acn-dgopa** [comment]
Nå er det fikset og tilgjengelig i AT22

**Comment by Nyeng** [comment]
Gjennomgått på refinement, verifisert manuelt og via systemintegrasjonstest.
